services:
  subgenai:
    depends_on:
      bazarr:
        condition: service_healthy
    image: 'mccloud/subgen:latest'
    container_name: subgenai
    volumes:
      - '${subgenai_data_folder}/models:/subgen/models'
      - '${subgenai_data_folder}/subgen.env:/subgen/subgen.env:ro'
    environment:
      LOG_LEVEL: debug
      NAME_SERVERS: 9.9.9.9
      PROCADDEDMEDIA: true
      PROCMEDIAONPLAY: false
      PLEXTOKEN: plextoken
      PLEXSERVER: 'http://127.0.0.1:32400'
      CONCURRENT_TRANSCRIPTIONS: 2
      USE_PATH_MAPPING: false
      MODEL_PATH: ./models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
